### ISSUE TITLE
latest musl-cross precompiled downloads lack kernel header include dirs

### ISSUE THREAD

**Issue by rofl0r** [GregorR/musl-cross#30]
using the prebuilt downloads:
```
/tmp/mips-sf-linux-musl $ find . -name linux
/tmp/mips-sf-linux-musl $
```

using my self-built toolchain:
```
$ find /home/rofl/musl-cross-4.8.3/mips-sf-linux-musl/ -name linux
/home/rofl/musl-cross-4.8.3/mips-sf-linux-musl/mips-sf-linux-musl/include/linux
```

**Comment by bradfa** [comment]
The root of this seems to be that when the Linux kernel headers directory gets created in the bootstrap, the directory is called `kernel-headers-$VERSION` but the cleanup function tries to remove the `configured`, `build`, `built`, and `installed` files from a directory called `linux-*`.

This naming confusion seems to happen because `defs.sh` specifies by default to fetch the kernel headers from sabotage which has a basename of `kernel-headers-$VERSION` but there is a commented out line just above this which would fetch from kernel.org and end up using the basename of `linux-$VERSION`.

This seems like it can be fixed in 2 different ways:
1. Find a new way to generate the `$(LINUX_HEADERS_DIR)` variable.
2. Don't use sabotage kernel-headers (or get sabotage to rename their kernel headers tarball)

**Comment by bradfa** [comment]
This appears to have been broken when 85c89b67314ad29d444d60373c51f0db78d0a247 was committed.

**Comment by GregorR** [comment]
Or, y'know... por que no los dos? d91a66ca
